apiVersion: apps/v1
kind: Deployment
metadata:
  name: lims-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lims-frontend
  template:
    metadata:
      name: lims-frontend
      labels:
        app: lims-frontend
    spec:
      containers:
        - image: localhost:5000/lims-frontend:3.0.0
          name: lims-frontend
          ports:
            - port: 8080
      # tolerations:
      #   - key: "node-role.kubernetes.io/master"
      #     effect: "NoSchedule"
      #     operator: "Exists"
